---
title: "data_viz"
author: "Laura Menicacci"
date: "2023-03-16"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)

df <- read_csv(".\\model_spec\\df.csv")
```

# Descriptive plots


## Boxplot - by year
```{r, echo=FALSE,fig.height=8,fig.width=8}
# Basic box plot

df$prio_year.factor <- factor(df$prio_year)

box_plot_by_year <- ggplot(df) + 
  geom_boxplot(mapping = aes(x = prio_year.factor,
                             y = patent_count), 
               outlier.colour="red",
                outlier.size=1) +
  labs(x = "Priority filing year", y =  "Patent count") + theme_bw() + ggtitle("International US patent counts (Y02E class)", subtitle = "Distribution over time") 

box_plot_by_year

ggsave(".\\fig_new\\box_plot_by_year.png", plot = box_plot_by_year, device = "png", width = 10, height = 10)

```

## Boxplot - by State
```{r, fig.height=8,fig.width=8}

box_plot_by_state <- df %>% 
  group_by(state_name) %>% 
  ggplot(aes(y = patent_count)) +
  geom_boxplot(outlier.colour="red",
               outlier.size=1) +
  facet_wrap(~state_name, scales = "free_y") +
  labs(x = "Priority filing year", y =  "Patent count") + 
  theme_bw() + 
  ggtitle("International US patent counts (Y02E class)", subtitle = "Distribution by State") 

box_plot_by_state

# ggsave(".\\figs_new\\box_plot_by_year.png", plot = box_plot_by_year, device = "png", width = 10, height = 10)

```
## Non-patenting states selection

Mechanical: scegli tutti gli stati che 
```{r}
df %>% 
  ggplot(aes(x = patent_count))+ geom_boxplot()
```
## Find out which states have a distribution that is within the first percentile range

```{r}
q25 <- quantile(df$patent_count, 0.25)

max_pat <- df %>% # max patent count 
  select(state_name, patent_count) %>% 
  group_by(state_name) %>% 
  summarise(max = max(patent_count, na.rm=TRUE))

nonpat_q25 <- c() # only Alaska

for (i in 1:nrow(max_pat)){
  if (max_pat[i, 2] <= q25[[1]]){
    nonpat_q25 <- append(nonpat_q25, max_pat[[i, 1]]) 
                       }
}

median <- median(df$patent_count)

nonpat_median <- c() 

for (i in 1:nrow(max_pat)){
  if (max_pat[i, 2] <= median){
    nonpat_median <- append(nonpat_median, max_pat[[i, 1]]) 
                       }
}


# df %>% 
# group_by(state_name) %>% 

# group by state + crea stat con massimi val per ogni stato + se il max è min o uguale al q25 allora appendi nella lista --> sottrai gli stati nella lista dalla lista tot us states

#

```



## Visualize distribution
```{r}
y_dist <- df %>% 
  ggplot(aes(x = patent_count)) +
  geom_histogram(fill = "navy", colour = "black") +
  labs(x = "Dependent variable (y) = patent counts", y = "") + 
  ggtitle("Distribution of the dependent variable")+
  theme_bw()

y_dist

ggsave(".\\fig_new\\y_distribution.png", plot = y_dist, device = "png", width = 8, height = 8)
  
```

