---
title: "all"
author: "Laura Menicacci"
date: "2023-03-16"
output: html_document
---
# Libraries
```{r}
library(tidyverse)
library(gets)
library(getspanel)
library(here)
library(doParallel)
library(readxl)

### for auto-tabs

library(grid)
library(gridExtra)
```

# Model with all data manipulations:
- logs
- ihs
- samples: gdp high & gdp low states
```{r}

df <- read_csv(".\\df.csv", show_col_types = FALSE)

df2 <- df %>% mutate(ihs_patent_count = asinh(patent_count), 
                     log_patent_count = log(patent_count +1) )


samples <- list(gdp_high, gdp_low)

```


## Functional forms - w/o logged y 
```{r}
controls <- c(" ~ gdp + pop + avg_temp + fuel", 
              " ~ lgdp + gdp_sq + lpop + lgdp_sq + avg_temp + lfuel") 

dep_var <- c( "patent_count", "ihs_patent_count") 

base_forms <- paste0(rep(dep_var, each = length(controls)), controls)

base_forms

```


## Model 
```{r}

cl <- makeCluster(4)
registerDoParallel(cl)

models <- foreach(f = base_forms, .combine = rbind, .packages = c('tidyverse', 'getspanel')) %:%
  foreach(smpl = c(1, 2), .combine = rbind) %:%
  foreach(a = c(0,1), .combine = rbind) %:%
  #foreach(b = c(10, 20, 30), .combine = rbind) %:%
  foreach(p.value = c(0.01, 0.001), .combine = rbind, .errorhandling = "remove") %dopar% {
    dat <- df2 %>% filter(state_name %in% samples[[smpl]])
      is <- isatpanel(
            data = dat,
            formula = as.formula(f),
            index = c("state_name", "prio_year"),
            effect = "twoways",
            iis = TRUE,
            fesis = TRUE,
            ar = a,
            t.pval = p.value,
            max.block.size = 20
            )
          models = tibble(source = f, 
                          state_sample = smpl,
                          year_range = paste0(min(df2$prio_year),":",max(df2$prio_year)), 
                          p_val = p.value, 
                          is = list(is),
                          iis = TRUE,
                          b_size = 20,
                          ar = a)
  }

stopCluster(cl)

saveRDS(models, ".\\results\\logs_ytrans_samples.RDS")

```

## Results
```{r}

models

```

## Results
```{r}
#for (i in 1:nrow(levels_y_trans)){
#  print(levels_y_trans$is[[i]])
#}

models$is[[28]] # high income countries, ar = 1, logs, pval = 0.001, ihs y

models$is[[26]] # high income countries, ar = 0, logs, pval = 0.001, ihs y


models$is[[32]] # low income countries, ar = 1, logs, pval = 0.001, ihs y


models$is[[30]] # low income countries, ar = 0, logs, pval = 0.001, ihs y

```



## Visualize high-VS-low gdp countries AR1/AR0
```{r}

models <- readRDS(".\\results\\logs_ytrans_samples.RDS")

y_transf_logs_sample_high <- plot(models$is[[27]]) # high income countries, ar = 1, logs, pval = 0.001, ihs y

ggsave("y_transf_logs_sample_high.png", plot = y_transf_logs_sample_high, device = "png", width = 10, height = 10)

#plot(models$is[[26]]) # high income countries, ar = 0, logs, pval = 0.001, ihs y


y_transf_logs_sample_low <- plot(models$is[[31]]) # low income countries, ar = 1, logs, pval = 0.001, ihs y

ggsave("y_transf_logs_sample_low.png", plot = y_transf_logs_sample_low, device = "png", width = 10, height = 10)


#(models$is[[30]]) # low income countries, ar = 0, logs, pval = 0.001, ihs y

```


## Plot residuals
```{r}
plot_residuals(models$is[[28]]) # high income countries, ar = 1, logs, pval = 0.001, ihs y

plot_residuals(models$is[[32]]) # low income countries, ar = 1, logs, pval = 0.001, ihs y
```
# plot levels
```{r}
plot(models$is[[4]]) # patent_count ~ gdp + pop + avg_temp + fuel, high incomw, pval = 0.010, ar=1

plot(models$is[[8]]) # levels
```

## check n of cores available for parall 
```{r}
num_of_cores <- detectCores()
data_per_core <- floor(nrow(df2)/num_of_cores)

num_of_cores
data_per_core
```

## Model - try without non-patenting states

Alaska, Mississippi, North Dakota, West Virginia, Wyoming

```{r}
nonpat <- c("Alaska", "Mississippi", "North Dakota", "West Virginia", "Wyoming")


df3 <- df2 %>% 
  filter(!(state_name %in% nonpat)) %>% 
  filter(prio_year <= 2019)
```


```{r}
controls <- c(" ~ lgdp + gdp_sq + lpop + lgdp_sq + avg_temp + lfuel") # " ~ gdp + pop + avg_temp + fuel", 

dep_var <- c( "patent_count", "ihs_patent_count") 

base_forms <- paste0(rep(dep_var, each = length(controls)), controls)


cl <- makeCluster(3)
registerDoParallel(cl)

models_nonpat <- foreach(f = base_forms, .combine = rbind, .packages = c('tidyverse', 'getspanel')) %:%
  #foreach(smpl = c(1, 2), .combine = rbind) %:%
  foreach(a = c(0,1), .combine = rbind) %:%
  #foreach(b = c(10, 20, 30), .combine = rbind) %:%
  foreach(p.value = c(0.01), .combine = rbind, .errorhandling = "remove") %dopar% {
    dat <- df3
      is <- isatpanel(
            data = dat,
            formula = as.formula(f),
            index = c("state_name", "prio_year"),
            effect = "twoways",
            iis = TRUE,
            fesis = TRUE,
            ar = a,
            t.pval = p.value,
            max.block.size = 20
            )
          models_nonpat = tibble(source = f, 
                          #state_sample = smpl,      
                          year_range = paste0(min(df3$prio_year),":",max(df3$prio_year)),
                          p_val = p.value, 
                          is = list(is),
                          iis = TRUE,
                          b_size = 20,
                          ar = a)
  }

stopCluster(cl)

saveRDS(models_nonpat, ".\\results\\models_nonpat.RDS")

```

## Viz fit
```{r, fig.height=10, fig.width=10}

plot(models_nonpat$is[[2]])


```

