---
title: "build modeling specification pipeline"
author: "Laura Menicacci"
date: "`r Sys.Date()`"
output: html_document
---

# Libraries

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(tidyverse)
library(gets)
library(getspanel)
library(here)
library(doParallel)
library(readxl)
library(gdata)

```

# Create controls

```{r}

df <- read_csv(".\\df.csv", show_col_types = FALSE)

df2 <- df %>% 
  mutate(lpop = log(pop),
         lgdp = log(gdp),
         lfuel = log(fuel),
         lgdp_sq = log(gdp)^2,
         ltemp = log(avg_temp),
         ihs_patent_count = asinh(patent_count), # inverse hyperbolic sine transformation
         log_patent_count = log(patent_count+1)) %>% # log+1 transformation
  filter(prio_year >= 2000)

# Sanity check
df2 %>% pull(state_name) %>% unique

df2 %>% filter(!complete.cases(.))

# write_csv(df2, ".\\df.csv")

```

# Load samples

```{r}
us_all <- c("Alabama", "Alaska", "Arizona", "Arkansas","California","Colorado","Connecticut", "Delaware", "Florida","Georgia","Idaho","Illinois","Indiana","Iowa","Kansas","Kentucky","Louisiana","Maine","Maryland","Massachusetts","Michigan","Minnesota","Mississippi","Missouri","Montana","Nebraska","Nevada","New Hampshire","New Jersey", "New York", "New Mexico", "North Carolina", "North Dakota","Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina","South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington","West Virginia","Wisconsin","Wyoming", "District of Columbia", "Hawaii")

us_q20 <- c("Alabama", "Arizona", "Arkansas","California","Colorado","Connecticut", "Delaware", "Florida","Georgia","Idaho","Illinois","Indiana","Iowa","Kansas","Kentucky","Louisiana","Maine","Maryland","Massachusetts","Michigan","Minnesota","Missouri","Nebraska","Nevada","New Hampshire","New Jersey", "New York", "New Mexico", "North Carolina", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina","South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington","Wisconsin", "District of Columbia", "Hawaii")

us_q25 <- c("Alabama", "Arizona", "California","Colorado","Connecticut", "Delaware", "Florida","Georgia","Idaho","Illinois","Indiana","Iowa","Kansas","Kentucky","Louisiana","Maine","Maryland","Massachusetts","Michigan","Minnesota","Missouri","Nevada","New Hampshire","New Jersey", "New York", "New Mexico", "North Carolina", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina","South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington","Wisconsin", "District of Columbia", "Hawaii")

us_q30 <- c( "Arizona","California","Colorado","Connecticut", "Delaware", "Florida","Georgia","Idaho","Illinois","Indiana","Iowa","Kentucky","Maryland","Massachusetts","Michigan","Minnesota","Missouri","Nevada","New Hampshire","New Jersey", "New York", "New Mexico", "North Carolina", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "Tennessee", "Texas", "Utah","Virginia", "Washington","Wisconsin", "District of Columbia")

samples <- mget(c("us_all", "us_q20", "us_q25", "us_q30"))
```

# Functional forms

```{r}

controls <- c(" ~ lgdp + lpop + lgdp_sq ") 

dep_var <- c("log_patent_count") # ihs selected as robustness check

base_forms <- paste0(rep(dep_var, each = length(controls)), controls)

base_forms

```

## Analysis

```{r}

cl <- makeCluster(6)
registerDoParallel(cl)

models <- foreach(f = base_forms, .combine = rbind, .packages = c('tidyverse', 'getspanel')) %:%
  foreach(smpl = c("us_all", "us_q25"), .combine = rbind) %:%
  foreach(a = c(0,1), .combine = rbind) %:%
  #foreach(b = c(10, 20, 30), .combine = rbind) %:%
  foreach(p.value = c(0.01, 0.05), .combine = rbind, .errorhandling = "remove") %dopar% {
    dat <- df2 %>% filter(state_name %in% samples[[smpl]])
      is <- isatpanel(
            data = dat,
            formula = as.formula(f),
            index = c("state_name", "prio_year"),
            effect = "twoways",
            iis = TRUE,
            fesis = TRUE,
            ar = a,
            t.pval = p.value,
            max.block.size = 20
            )
          models = tibble(source = f, 
                          state_sample = smpl,      
                          year_range = paste0(min(df2$prio_year),":",max(df2$prio_year)),
                          p_val = p.value, 
                          is = list(is),
                          iis = TRUE,
                          b_size = 20,
                          ar = a)
  }

stopCluster(cl)

saveRDS(models, ".\\results\\models_nonpat_q25.RDS")
```

## Analysis: exclude 2020

```{r}
cl <- makeCluster(6)
registerDoParallel(cl)

models <- foreach(f = base_forms, .combine = rbind, .packages = c('tidyverse', 'getspanel')) %:%
  foreach(smpl = c("us_q30"), .combine = rbind) %:%
  foreach(a = c(0,1), .combine = rbind) %:%
  #foreach(b = c(10, 20, 30), .combine = rbind) %:%
  foreach(p.value = c(0.01, 0.05), .combine = rbind, .errorhandling = "remove") %dopar% {
    dat <- df2 %>% filter(state_name %in% samples[[smpl]]) %>% filter(prio_year <= 2019)
      is <- isatpanel(
            data = dat,
            formula = as.formula(f),
            index = c("state_name", "prio_year"),
            effect = "twoways",
            iis = TRUE,
            fesis = TRUE,
            ar = a,
            t.pval = p.value,
            max.block.size = 20
            )
          models = tibble(source = f, 
                          state_sample = smpl,      
                          year_range = paste0(min(dat$prio_year),":",max(dat$prio_year)),
                          p_val = p.value, 
                          is = list(is),
                          iis = TRUE,
                          b_size = 20,
                          ar = a)
  }

stopCluster(cl)

saveRDS(models, ".\\results\\mods_main_updatedpackage.RDS")
```


## Analysis: silence IIS 

```{r}
cl <- makeCluster(6)
registerDoParallel(cl)

models <- foreach(f = base_forms, .combine = rbind, .packages = c('tidyverse', 'getspanel')) %:%
  foreach(smpl = c("us_q30"), .combine = rbind) %:%
  foreach(a = c(0,1), .combine = rbind) %:%
  #foreach(b = c(10, 20, 30), .combine = rbind) %:%
  foreach(p.value = c(0.01, 0.05), .combine = rbind, .errorhandling = "remove") %dopar% {
    dat <- df2 %>% filter(state_name %in% samples[[smpl]]) %>% filter(prio_year <= 2019)
      is <- isatpanel(
            data = dat,
            formula = as.formula(f),
            index = c("state_name", "prio_year"),
            effect = "twoways",
            iis = FALSE,
            fesis = TRUE,
            ar = a,
            t.pval = p.value,
            max.block.size = 20
            )
          models = tibble(source = f, 
                          state_sample = smpl,      
                          year_range = paste0(min(dat$prio_year),":",max(dat$prio_year)),
                          p_val = p.value, 
                          is = list(is),
                          iis = FALSE,
                          b_size = 20,
                          ar = a)
  }

stopCluster(cl)

saveRDS(models, ".\\results\\mods_main_updatedpackage_noIIS.RDS")
```


## Analysis: robustness  check

Selected model specifications + includes all controls: fuel

```{r}

# Functional forms

add_forms <- paste0(base_forms, "+ lfuel")

# Initialize model

cl <- makeCluster(6)
registerDoParallel(cl)

models <- foreach(f = add_forms, .combine = rbind, .packages = c('tidyverse', 'getspanel')) %:%
  foreach(smpl = c("us_all", "us_q30"), .combine = rbind) %:%
  foreach(a = c(0,1), .combine = rbind) %:%
  #foreach(b = c(10, 20, 30), .combine = rbind) %:%
  foreach(p.value = c(0.01, 0.05), .combine = rbind, .errorhandling = "remove") %dopar% {
    dat <- df2 %>% filter(state_name %in% samples[[smpl]]) %>% filter(prio_year <= 2019)
      is <- isatpanel(
            data = dat,
            formula = as.formula(f),
            index = c("state_name", "prio_year"),
            effect = "twoways",
            iis = TRUE,
            fesis = TRUE,
            ar = a,
            t.pval = p.value,
            max.block.size = 20
            )
          models = tibble(source = f, 
                          state_sample = smpl, 
                          year_range = paste0(min(dat$prio_year),":",max(dat$prio_year)), 
                          p_val = p.value, 
                          is = list(is),
                          iis = TRUE,
                          b_size = 20,
                          ar = a)
  }


saveRDS(models, ".\\results\\models_w_fuel.RDS")

```

