---
title: "Selected Results"
date: "`r Sys.Date()`"
output: 
  html_document:
    dev: ragg_png

---

```{r set-options, echo=FALSE, cache=FALSE}
options(width = 3000)
```

```{css, echo=FALSE}
pre {
  max-height: 300px;
  overflow-y: auto;
}

```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, max.height = '300px', fig.width = 16, fig.height = 8) #fig.show="hold",,

library(data.table)
library(tidyverse)
library(openxlsx)
library(gets)
library(getspanel)
library(here)
library(doParallel)
library(gridExtra)
library(conflicted)
library(viridis)
library(gplots)

conflict_prefer("filter", "dplyr")
conflict_prefer("first", "dplyr")
conflict_prefer("lag", "dplyr")

standard <- readRDS(here("model_spec/results/logs_ytrans_samples.RDS")) %>% 
  separate(source, into = c("dep","formula"), sep = "[~]", remove = FALSE) %>%
  mutate(dep = str_to_title(gsub("_"," ",trimws(dep))),
         formula = trimws(formula),
         mod_name = case_when(grepl("ihs", source) & grepl("gdp", source) ~ "Level controls",
                              !grepl("ihs", source) & grepl("lgdp", source) ~ "Log controls",
                              grepl("ihs", source) & grepl("lgdp", source) ~ "Log controls",
                              !grepl("ihs", source) & grepl("gdp", source) ~ "Level controls"))
standard

```

```{r, include=FALSE}
# Plotting functions

f <- function(k) {
  step <- k
  function(y) seq(floor(min(y)), ceiling(max(y)), by = step)
}

# Arranges result plots (plot and plot_grid) and prints model results
# Option to suppress model results using results = FALSE is required for automatic tabsetting.
gen_p <- function(df, results = TRUE, auto = FALSE){
  if(nrow(df) == 0){return("Empty data frame. Model likely not run.")}else{
    for(i in 1:nrow(df)){
      mt <- paste0(df$state_sample[i], " (", df$year_range[i],")", "; p.value: ",df$p_val[i],  "; AR: ",df$ar[i])
      st <- paste0("Formula: ", df$source[i])
      
      res <- df %>% slice(i) %>% pull(is) %>% first
      
      pl <- res %>% 
        plot(zero_line = FALSE) +
        ggtitle(label = mt, subtitle = st) +
        scale_x_continuous(breaks = f(10))
      
      pg <- res %>%
        plot_grid() +
        ggtitle(label = mt, subtitle = st)
      grid.arrange(pl, pg, ncol = 2)
      
      if(results == TRUE & auto == FALSE){
        print(st)
        print(mt)
        print(res)
      }else if(results == TRUE & auto == TRUE){
        p <- invisible(capture.output(res$isatpanel.result))
        # Spacing included to trick knitr into reading as verbatim code.
        cat(c("                         \n", 
              "                         \n", 
              paste("                  ", st,'     \n'),
              paste("                  ", mt,'     \n'),
              paste("                  ", p,'     \n')))
      }
    }
  }
}
```



# Overview: Preliminary results {.tabset}

Models results from last meeting. 
You can find models divided by AR term (0,1), type of dependent variable, state sample, and p-value level (0.01, 0.001).  

The two states samples are indicated with 1 and 2, where: 1 = high income states, 2 = low income states. 

## AR0 {.tabset}


```{r prelim, echo = FALSE, results = 'asis', cache = TRUE}

 standard %>%
  filter(ar == 0) %>% 
       dplyr::group_split(dep) %>%
       purrr::iwalk(.,~{
         name <- unique(.x$dep)
         cat('### ', name, '{.tabset}   \n')
              for(p in unique(.x$p_val)){
                   cat('#### ', p, '{.tabset}   \n')
                for(sm in unique(.x$state_sample)){
                   cat('##### ', sm, '{.tabset}   \n')
                   filter(.x, state_sample == sm & p_val == p) %>% gen_p(., auto = TRUE)
                cat('\n')
                cat('\n')
                }
           cat('\n')
           cat('\n')
           }
         cat('\n')
         cat('\n')
       })

```

## AR1 {.tabset}

```{r prelimar, echo = FALSE, results = 'asis', cache = TRUE}


standard %>%
  filter(ar == 1)%>% 
       dplyr::group_split(dep) %>%
       purrr::iwalk(.,~{
         name <- unique(.x$dep)
         cat('### ', name, '{.tabset}   \n')
              for(p in unique(.x$p_val)){
                   cat('#### ', p, '{.tabset}   \n')
                for(sm in unique(.x$state_sample)){
                   cat('##### ', sm, '{.tabset}   \n')
                   filter(.x, state_sample == sm & p_val == p) %>% gen_p(., auto = TRUE)
                cat('\n')
                cat('\n')
                }
           cat('\n')
           cat('\n')
           }
         cat('\n')
         cat('\n')
       })


#for(sm in unique(.x$country_sample)){
#                  cat('#### ', sm, '{.tabset}   \n')
#                for(hte in unique(.x$hte_spec)){
#                  cat('##### ', hte, '{.tabset}   \n')
#                  filter(.x, country_sample == sm & hte_spec == hte) %>% gen_p(., auto = TRUE)
#                cat('\n')
#                cat('\n')

```
