---
title: "Model specifications"
author: "Laura Menicacci"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---
# Libraries

```{r, echo=FALSE}
library(tidyverse)
library(gets)
library(getspanel)
library(here)
library(doParallel)
library(readxl)

### for auto-tabs

library(grid)
library(gridExtra)

```

# Data & controls 
```{r, echo=FALSE}

df <- read_csv(".\\df.csv", show_col_types = FALSE)

```

# Statistical summary 
```{r}
stats <- df %>% summarise(across(where(is.numeric), .fns = 
                     list(min = min,
                          median = median,
                          mean = mean,
                          stdev = sd,
                          q25 = ~quantile(., 0.25),
                          q75 = ~quantile(., 0.75),
                          max = max))) %>%
  pivot_longer(everything())

stats

```


# Create US samples by gdp
```{r}

us_sample <- c("Alabama", "Alaska", "Arizona", "Arkansas","California","Colorado","Connecticut", "Delaware", "Florida","Georgia","Idaho","Illinois","Indiana","Iowa","Kansas","Kentucky","Louisiana","Maine","Maryland","Massachusetts","Michigan","Minnesota","Mississippi","Missouri","Montana","Nebraska","Nevada","New Hampshire","New Jersey", "New York", "New Mexico", "North Carolina", "North Dakota","Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina","South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington","West Virginia","Wisconsin","Wyoming", "District of Columbia", "Hawaii")

# create two samples on gdp 

gdp_median <- stats[[16, 2]]

# average gdp over time 

avg_gdp <- df %>% 
  select(state_name, gdp) %>% 
  group_by(state_name) %>% 
  summarise(mean = mean(gdp, na.rm=TRUE))

gdp_low <- c()
gdp_high<- c()

for (i in 1:nrow(avg_gdp)){
  if (avg_gdp[i, 2] >= gdp_median){
    gdp_high <- append(gdp_high, avg_gdp[[i, 1]]) # la mediana è un quantile
                       }  else {
    gdp_low <- append(gdp_low, avg_gdp[[i, 1]])
                      }
}

samples <- list(gdp_high, gdp_low) # for model iteration

df %>% 
  filter(state_name %in% gdp_high) %>% 
  ggplot(aes(x = patent_count)) + geom_histogram(colour = "black", fill= "lightblue") + theme_bw() + theme_bw() + ggtitle("Distribution per high income states")

df %>% 
  filter(state_name %in% gdp_low) %>% 
  ggplot(aes(x = patent_count)) + geom_histogram(colour = "black", fill= "lightblue") + theme_bw() + theme_bw() + ggtitle("Distribution per low income states")

```



## Create US samples by patent count

```{r}
# create two samples on patent count 

patent_count_median <- stats[[9, 2]]

# average y over time 

avg_y <- df %>% 
  select(state_name, patent_count) %>% 
  group_by(state_name) %>% 
  summarise(mean = mean(patent_count, na.rm=TRUE))

y_low <- c()
y_high<- c()

for (i in 1:nrow(avg_y)){
  if (avg_y[i, 2] >= patent_count_median){ 
    y_high <- append(y_high, avg_y[[i, 1]])
                       }  else {
    y_low <- append(y_low, avg_y[[i, 1]])
                      }
}


df %>% 
  filter(state_name %in% y_high) %>% 
  ggplot(aes(x = patent_count)) + geom_histogram(colour = "black", fill= "lightblue") + theme_bw() + theme_bw() + ggtitle("Distribution per high patenting states")

df %>% 
  filter(state_name %in% y_low) %>% 
  ggplot(aes(x = patent_count)) + geom_histogram(colour = "black", fill= "lightblue") + theme_bw() + theme_bw() + ggtitle("Distribution per low patenting states")

```



# Functional forms

```{r}
controls <- c(" ~ gdp + pop + avg_temp + fuel") 

dep_var <- c( "patent_count") 

base_forms <- paste0(rep(dep_var, each = length(controls)), controls)

base_forms
```

## Models by gdp group 

```{r, echo=FALSE, eval=FALSE}

cl <- makeCluster(4)
registerDoParallel(cl)

models <- foreach(f = base_forms, .combine = rbind, .packages = c('tidyverse', 'getspanel')) %:%
  foreach(smpl = c(1, 2), .combine = rbind) %:%
  foreach(a = c(0,1), .combine = rbind) %:%
  #foreach(b = c(10, 20, 30), .combine = rbind) %:%
  foreach(p.value = c(0.01), .combine = rbind, .errorhandling = "remove") %dopar% {
    dat <- df %>% filter(state_name %in% samples[[smpl]])
      is <- isatpanel(
            data = dat,
            formula = as.formula(f),
            index = c("state_name", "prio_year"),
            effect = "twoways",
            iis = TRUE,
            fesis = TRUE,
            ar = a,
            t.pval = p.value,
            max.block.size = 20
            )
          models = tibble(source = f, 
                          state_sample = smpl,
                          year_range = paste0(min(df2$prio_year),":",max(df2$prio_year)), 
                          p_val = p.value, 
                          is = list(is),
                          iis = TRUE,
                          b_size = 20,
                          ar = a)
  }

saveRDS(models, ".\\results\\levels_gdp_samples.RDS")

```

# prova da canc dopo 
```{r}

samples <- list(gdp_high, gdp_low) # for model iteration

smpl <- c("1", "2")

df %>% filter(state_name %in% samples[[smpl]])
```




## have a look
```{r}
for (i in 1:nrow(models)){
  print(models$is[[i]])
}

```


## plot
```{r}

plot(models$is[[1]])

plot(models$is[[2]])

plot(models$is[[3]])

plot(models$is[[4]])

#plot(models$is[[5]])
#
#plot(models$is[[6]])
#
#plot(models$is[[7]])
#
#plot(models$is[[8]])
#
#plot(models$is[[9]])


```
## Same without IIS 

```{r}
cl <- makeCluster(4)
registerDoParallel(cl)

models <- foreach(f = base_forms, .combine = rbind, .packages = c('tidyverse', 'getspanel')) %:%
  foreach(smpl = c(1, 2), .combine = rbind) %:%
  foreach(a = c(0,1), .combine = rbind) %:%
  #foreach(b = c(10, 20, 30), .combine = rbind) %:%
  foreach(p.value = c(0.01), .combine = rbind, .errorhandling = "remove") %dopar% {
    dat <- df %>% filter(state_name %in% samples[[smpl]])
      is <- isatpanel(
            data = dat,
            formula = as.formula(f),
            index = c("state_name", "prio_year"),
            effect = "twoways",
            iis = FALSE,
            fesis = TRUE,
            ar = a,
            t.pval = p.value,
            max.block.size = 20
            )
          models = tibble(source = f, 
                          state_sample = smpl,
                          year_range = paste0(min(df2$prio_year),":",max(df2$prio_year)), 
                          p_val = p.value, 
                          is = list(is),
                          iis = FALSE,
                          b_size = 20,
                          ar = a)
  }

saveRDS(models, ".\\results\\levels_gdp_samples_noIIS.RDS")

```

```{r}
samples_noIIS <- readRDS(".\\results\\levels_gdp_samples_noIIS.RDS")

for (i in 1:nrow(samples_noIIS)){
  print(samples_noIIS$is[[i]])
}
```


```{r}
plot(samples_noIIS$is[[1]])

plot(samples_noIIS$is[[2]])

plot(samples_noIIS$is[[3]])

plot(samples_noIIS$is[[4]])

```
## Plot residuals
```{r}
model_gdp_samples <- readRDS(".\\results\\levels_gdp_samples.RDS")

#plot_residuals(levels_y_transformations$is[[5]])

plot_residuals(model_gdp_samples$is[[1]])

plot_residuals(model_gdp_samples$is[[2]])

plot_residuals(model_gdp_samples$is[[3]])

plot_residuals(model_gdp_samples$is[[4]])

```
## Drop non-patenting states

### Low gdp 
```{r}

box_plot_by_low_gdp <- df %>% 
  filter(state_name %in% gdp_low) %>% 
  ggplot(aes(y = patent_count)) +
  geom_boxplot(outlier.colour="red",
               outlier.size=1) +
  facet_wrap(~state_name, scales = "free_y") +
  labs(x = "Priority filing year", y =  "Patent count") + 
  theme_bw() + 
  ggtitle("International US patent counts (Y02E class)", subtitle = "Distribution by low income state") 

box_plot_by_low_gdp


```

### High gdp 
```{r}
box_plot_by_high_gdp <- df %>% 
  filter(state_name %in% gdp_high) %>% 
  ggplot(aes(y = patent_count)) +
  geom_boxplot(outlier.colour="red",
               outlier.size=1) +
  facet_wrap(~state_name, scales = "free_y") +
  labs(x = "Priority filing year", y =  "Patent count") + 
  theme_bw() + 
  ggtitle("International US patent counts (Y02E class)", subtitle = "Distribution by high income state") 

box_plot_by_high_gdp

```
